// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/order-deal/order-deal.proto

package com_toyent_srv_orderdeal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OrderDeal service

type OrderDealService interface {
}

type orderDealService struct {
	c    client.Client
	name string
}

func NewOrderDealService(name string, c client.Client) OrderDealService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "com.toyent.srv.orderdeal"
	}
	return &orderDealService{
		c:    c,
		name: name,
	}
}

// Server API for OrderDeal service

type OrderDealHandler interface {
}

func RegisterOrderDealHandler(s server.Server, hdlr OrderDealHandler, opts ...server.HandlerOption) error {
	type orderDeal interface {
	}
	type OrderDeal struct {
		orderDeal
	}
	h := &orderDealHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderDeal{h}, opts...))
}

type orderDealHandler struct {
	OrderDealHandler
}
