// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package com_toyent_srv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HoldOrder struct {
	StockId              string   `protobuf:"bytes,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	HoldNumber           int32    `protobuf:"varint,2,opt,name=hold_number,json=holdNumber,proto3" json:"hold_number,omitempty"`
	HoldPrice            float64  `protobuf:"fixed64,3,opt,name=hold_price,json=holdPrice,proto3" json:"hold_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoldOrder) Reset()         { *m = HoldOrder{} }
func (m *HoldOrder) String() string { return proto.CompactTextString(m) }
func (*HoldOrder) ProtoMessage()    {}
func (*HoldOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{0}
}

func (m *HoldOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoldOrder.Unmarshal(m, b)
}
func (m *HoldOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoldOrder.Marshal(b, m, deterministic)
}
func (m *HoldOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoldOrder.Merge(m, src)
}
func (m *HoldOrder) XXX_Size() int {
	return xxx_messageInfo_HoldOrder.Size(m)
}
func (m *HoldOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_HoldOrder.DiscardUnknown(m)
}

var xxx_messageInfo_HoldOrder proto.InternalMessageInfo

func (m *HoldOrder) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

func (m *HoldOrder) GetHoldNumber() int32 {
	if m != nil {
		return m.HoldNumber
	}
	return 0
}

func (m *HoldOrder) GetHoldPrice() float64 {
	if m != nil {
		return m.HoldPrice
	}
	return 0
}

type UserOrder struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StockId              string   `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	OrderType            int32    `protobuf:"varint,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	OrderNumber          int32    `protobuf:"varint,4,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	DealNumber           int32    `protobuf:"varint,5,opt,name=deal_number,json=dealNumber,proto3" json:"deal_number,omitempty"`
	OrderPrice           float64  `protobuf:"fixed64,6,opt,name=order_price,json=orderPrice,proto3" json:"order_price,omitempty"`
	OrderStatus          int32    `protobuf:"varint,7,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserOrder) Reset()         { *m = UserOrder{} }
func (m *UserOrder) String() string { return proto.CompactTextString(m) }
func (*UserOrder) ProtoMessage()    {}
func (*UserOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{1}
}

func (m *UserOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOrder.Unmarshal(m, b)
}
func (m *UserOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOrder.Marshal(b, m, deterministic)
}
func (m *UserOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOrder.Merge(m, src)
}
func (m *UserOrder) XXX_Size() int {
	return xxx_messageInfo_UserOrder.Size(m)
}
func (m *UserOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UserOrder proto.InternalMessageInfo

func (m *UserOrder) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *UserOrder) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

func (m *UserOrder) GetOrderType() int32 {
	if m != nil {
		return m.OrderType
	}
	return 0
}

func (m *UserOrder) GetOrderNumber() int32 {
	if m != nil {
		return m.OrderNumber
	}
	return 0
}

func (m *UserOrder) GetDealNumber() int32 {
	if m != nil {
		return m.DealNumber
	}
	return 0
}

func (m *UserOrder) GetOrderPrice() float64 {
	if m != nil {
		return m.OrderPrice
	}
	return 0
}

func (m *UserOrder) GetOrderStatus() int32 {
	if m != nil {
		return m.OrderStatus
	}
	return 0
}

type QueryOrderRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId              int64    `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StockId              string   `protobuf:"bytes,4,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrderRequest) Reset()         { *m = QueryOrderRequest{} }
func (m *QueryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOrderRequest) ProtoMessage()    {}
func (*QueryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{2}
}

func (m *QueryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderRequest.Unmarshal(m, b)
}
func (m *QueryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderRequest.Marshal(b, m, deterministic)
}
func (m *QueryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderRequest.Merge(m, src)
}
func (m *QueryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOrderRequest.Size(m)
}
func (m *QueryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderRequest proto.InternalMessageInfo

func (m *QueryOrderRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryOrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *QueryOrderRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *QueryOrderRequest) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

type QueryOrderResponse struct {
	Sid                  string       `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Order                []*UserOrder `protobuf:"bytes,4,rep,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryOrderResponse) Reset()         { *m = QueryOrderResponse{} }
func (m *QueryOrderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOrderResponse) ProtoMessage()    {}
func (*QueryOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{3}
}

func (m *QueryOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderResponse.Unmarshal(m, b)
}
func (m *QueryOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderResponse.Marshal(b, m, deterministic)
}
func (m *QueryOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderResponse.Merge(m, src)
}
func (m *QueryOrderResponse) XXX_Size() int {
	return xxx_messageInfo_QueryOrderResponse.Size(m)
}
func (m *QueryOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderResponse proto.InternalMessageInfo

func (m *QueryOrderResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryOrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryOrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryOrderResponse) GetOrder() []*UserOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StockId              string   `protobuf:"bytes,3,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	OrderType            int32    `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	OrderNumber          int32    `protobuf:"varint,5,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	OrderPrice           float64  `protobuf:"fixed64,6,opt,name=order_price,json=orderPrice,proto3" json:"order_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{4}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *OrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrderRequest) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

func (m *OrderRequest) GetOrderType() int32 {
	if m != nil {
		return m.OrderType
	}
	return 0
}

func (m *OrderRequest) GetOrderNumber() int32 {
	if m != nil {
		return m.OrderNumber
	}
	return 0
}

func (m *OrderRequest) GetOrderPrice() float64 {
	if m != nil {
		return m.OrderPrice
	}
	return 0
}

type OrderResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	OrderId              int64    `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{5}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderResponse) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type QueryHoldRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StockId              string   `protobuf:"bytes,3,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryHoldRequest) Reset()         { *m = QueryHoldRequest{} }
func (m *QueryHoldRequest) String() string { return proto.CompactTextString(m) }
func (*QueryHoldRequest) ProtoMessage()    {}
func (*QueryHoldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{6}
}

func (m *QueryHoldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryHoldRequest.Unmarshal(m, b)
}
func (m *QueryHoldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryHoldRequest.Marshal(b, m, deterministic)
}
func (m *QueryHoldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHoldRequest.Merge(m, src)
}
func (m *QueryHoldRequest) XXX_Size() int {
	return xxx_messageInfo_QueryHoldRequest.Size(m)
}
func (m *QueryHoldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHoldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHoldRequest proto.InternalMessageInfo

func (m *QueryHoldRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryHoldRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *QueryHoldRequest) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

type QueryHoldResponse struct {
	Sid                  string       `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	HoldOrder            []*HoldOrder `protobuf:"bytes,4,rep,name=hold_order,json=holdOrder,proto3" json:"hold_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryHoldResponse) Reset()         { *m = QueryHoldResponse{} }
func (m *QueryHoldResponse) String() string { return proto.CompactTextString(m) }
func (*QueryHoldResponse) ProtoMessage()    {}
func (*QueryHoldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{7}
}

func (m *QueryHoldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryHoldResponse.Unmarshal(m, b)
}
func (m *QueryHoldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryHoldResponse.Marshal(b, m, deterministic)
}
func (m *QueryHoldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHoldResponse.Merge(m, src)
}
func (m *QueryHoldResponse) XXX_Size() int {
	return xxx_messageInfo_QueryHoldResponse.Size(m)
}
func (m *QueryHoldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHoldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHoldResponse proto.InternalMessageInfo

func (m *QueryHoldResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryHoldResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryHoldResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryHoldResponse) GetHoldOrder() []*HoldOrder {
	if m != nil {
		return m.HoldOrder
	}
	return nil
}

type CancelRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId              int64    `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRequest) Reset()         { *m = CancelRequest{} }
func (m *CancelRequest) String() string { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()    {}
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{8}
}

func (m *CancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRequest.Unmarshal(m, b)
}
func (m *CancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRequest.Marshal(b, m, deterministic)
}
func (m *CancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRequest.Merge(m, src)
}
func (m *CancelRequest) XXX_Size() int {
	return xxx_messageInfo_CancelRequest.Size(m)
}
func (m *CancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRequest proto.InternalMessageInfo

func (m *CancelRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *CancelRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CancelRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type CancelResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	OrderStatus          int32    `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DealNumber           int32    `protobuf:"varint,5,opt,name=deal_number,json=dealNumber,proto3" json:"deal_number,omitempty"`
	UndealNumber         int32    `protobuf:"varint,6,opt,name=undeal_number,json=undealNumber,proto3" json:"undeal_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelResponse) Reset()         { *m = CancelResponse{} }
func (m *CancelResponse) String() string { return proto.CompactTextString(m) }
func (*CancelResponse) ProtoMessage()    {}
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{9}
}

func (m *CancelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelResponse.Unmarshal(m, b)
}
func (m *CancelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelResponse.Marshal(b, m, deterministic)
}
func (m *CancelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelResponse.Merge(m, src)
}
func (m *CancelResponse) XXX_Size() int {
	return xxx_messageInfo_CancelResponse.Size(m)
}
func (m *CancelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelResponse proto.InternalMessageInfo

func (m *CancelResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *CancelResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CancelResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CancelResponse) GetOrderStatus() int32 {
	if m != nil {
		return m.OrderStatus
	}
	return 0
}

func (m *CancelResponse) GetDealNumber() int32 {
	if m != nil {
		return m.DealNumber
	}
	return 0
}

func (m *CancelResponse) GetUndealNumber() int32 {
	if m != nil {
		return m.UndealNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*HoldOrder)(nil), "com.toyent.srv.order.HoldOrder")
	proto.RegisterType((*UserOrder)(nil), "com.toyent.srv.order.UserOrder")
	proto.RegisterType((*QueryOrderRequest)(nil), "com.toyent.srv.order.QueryOrderRequest")
	proto.RegisterType((*QueryOrderResponse)(nil), "com.toyent.srv.order.QueryOrderResponse")
	proto.RegisterType((*OrderRequest)(nil), "com.toyent.srv.order.OrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "com.toyent.srv.order.OrderResponse")
	proto.RegisterType((*QueryHoldRequest)(nil), "com.toyent.srv.order.QueryHoldRequest")
	proto.RegisterType((*QueryHoldResponse)(nil), "com.toyent.srv.order.QueryHoldResponse")
	proto.RegisterType((*CancelRequest)(nil), "com.toyent.srv.order.CancelRequest")
	proto.RegisterType((*CancelResponse)(nil), "com.toyent.srv.order.CancelResponse")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor_986e030a471601a2) }

var fileDescriptor_986e030a471601a2 = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcb, 0x6e, 0xd3, 0x50,
	0x10, 0xe5, 0xd6, 0x2f, 0x3c, 0x49, 0x50, 0xb9, 0x42, 0xd4, 0x44, 0xaa, 0x12, 0x6e, 0x11, 0xf5,
	0xca, 0x48, 0x45, 0x6c, 0xd9, 0xb0, 0xa1, 0x1b, 0x1e, 0x86, 0x48, 0xac, 0x88, 0xdc, 0xf8, 0x02,
	0x15, 0x89, 0x6d, 0x7c, 0x6d, 0xa4, 0x7c, 0x05, 0x4b, 0x3e, 0x85, 0x15, 0xff, 0xc3, 0x0f, 0xb0,
	0x47, 0x9e, 0xb1, 0x1d, 0x9b, 0xba, 0x0e, 0x12, 0xde, 0x44, 0x9e, 0xf1, 0xf1, 0x9c, 0x99, 0x33,
	0x8f, 0xc0, 0x51, 0x92, 0xc6, 0x59, 0xfc, 0x28, 0x4e, 0x43, 0x99, 0xd2, 0xaf, 0x87, 0x1e, 0x7e,
	0x67, 0x15, 0x6f, 0xbc, 0x2c, 0xde, 0xca, 0x28, 0xf3, 0x54, 0xfa, 0xd5, 0xc3, 0x77, 0xe2, 0x03,
	0xd8, 0xcf, 0xe3, 0x75, 0xf8, 0xb2, 0x30, 0xf8, 0x3d, 0xb8, 0xa9, 0xb2, 0x78, 0xf5, 0x79, 0x79,
	0x19, 0x3a, 0x6c, 0xce, 0x5c, 0xdb, 0xb7, 0xd0, 0x3e, 0x0f, 0xf9, 0x0c, 0x46, 0x9f, 0xe2, 0x75,
	0xb8, 0x8c, 0xf2, 0xcd, 0x85, 0x4c, 0x9d, 0x83, 0x39, 0x73, 0x0d, 0x1f, 0x0a, 0xd7, 0x0b, 0xf4,
	0xf0, 0x63, 0x40, 0x6b, 0x99, 0xa4, 0x97, 0x2b, 0xe9, 0x68, 0x73, 0xe6, 0x32, 0xdf, 0x2e, 0x3c,
	0xaf, 0x0a, 0x87, 0xf8, 0xc5, 0xc0, 0x5e, 0x28, 0x99, 0xd6, 0x44, 0x48, 0x5f, 0x11, 0x69, 0xbe,
	0x85, 0xf6, 0x79, 0xd8, 0xca, 0xe1, 0xa0, 0x9d, 0xc3, 0x31, 0x00, 0x7d, 0x95, 0x6d, 0x13, 0xa2,
	0x30, 0x7c, 0x1b, 0x3d, 0x6f, 0xb7, 0x89, 0xe4, 0xf7, 0x61, 0x4c, 0xaf, 0xcb, 0x1c, 0x75, 0x04,
	0x8c, 0xd0, 0x57, 0x26, 0x39, 0x83, 0x51, 0x28, 0x83, 0x75, 0x85, 0x30, 0xa8, 0x8a, 0xc2, 0xb5,
	0x03, 0x50, 0x0c, 0x2a, 0xc3, 0xc4, 0x32, 0x88, 0x15, 0xeb, 0xd8, 0x91, 0xa8, 0x2c, 0xc8, 0x72,
	0xe5, 0x58, 0x0d, 0x92, 0x37, 0xe8, 0x12, 0x19, 0xdc, 0x7e, 0x9d, 0xcb, 0x74, 0x8b, 0xa5, 0xfa,
	0xf2, 0x4b, 0x2e, 0x55, 0xc6, 0x0f, 0x41, 0x53, 0xb5, 0xaa, 0xc5, 0x23, 0x3f, 0x02, 0x2b, 0x57,
	0x24, 0x01, 0xd5, 0x69, 0x16, 0x26, 0x29, 0x50, 0x8b, 0xa3, 0x5d, 0x2f, 0x8e, 0xde, 0x12, 0x47,
	0x7c, 0x63, 0xc0, 0x9b, 0xb4, 0x2a, 0x89, 0x23, 0x25, 0x3b, 0x78, 0xef, 0x82, 0x59, 0xe6, 0x5e,
	0xd2, 0x92, 0xc5, 0x1d, 0xb0, 0x36, 0x52, 0xa9, 0xe0, 0x23, 0x49, 0x6b, 0xfb, 0x95, 0xc9, 0x9f,
	0x80, 0x81, 0x09, 0x38, 0xfa, 0x5c, 0x73, 0x47, 0x67, 0x33, 0xaf, 0x6b, 0x92, 0xbc, 0xba, 0xbb,
	0x3e, 0xa1, 0xc5, 0x0f, 0x06, 0xe3, 0xff, 0xd0, 0xa0, 0x2e, 0x54, 0xeb, 0x9b, 0x02, 0x7d, 0xdf,
	0x14, 0x18, 0x9d, 0x53, 0xd0, 0xdb, 0x64, 0x11, 0xc1, 0x64, 0x78, 0x15, 0x9b, 0x6d, 0xd5, 0x5b,
	0x6d, 0x15, 0xef, 0xe0, 0x10, 0x5b, 0x57, 0x6c, 0xe2, 0xa0, 0x62, 0x89, 0xef, 0xac, 0x1c, 0x46,
	0x0a, 0x3d, 0x60, 0x39, 0x4f, 0xcb, 0x7d, 0xff, 0x87, 0xc9, 0xa8, 0x0f, 0x0c, 0x1d, 0x04, 0x7c,
	0x14, 0x0b, 0x98, 0x3c, 0x0b, 0xa2, 0x95, 0x5c, 0x0f, 0xba, 0x21, 0xe2, 0x27, 0x83, 0x5b, 0x55,
	0xdc, 0x01, 0xab, 0xfd, 0x7b, 0xed, 0xf5, 0x2b, 0x6b, 0xbf, 0xff, 0xb6, 0x9c, 0xc0, 0x24, 0x8f,
	0x9a, 0x10, 0x13, 0x21, 0x63, 0x72, 0x12, 0xe8, 0xec, 0xf7, 0x01, 0x18, 0x74, 0x23, 0x03, 0x80,
	0xdd, 0x3e, 0xf3, 0xd3, 0x6e, 0x69, 0xaf, 0x1c, 0x9a, 0xa9, 0xbb, 0x1f, 0x48, 0xba, 0x88, 0x1b,
	0xdc, 0xaf, 0xb8, 0x44, 0xf7, 0x47, 0xad, 0xc0, 0x27, 0xbd, 0x98, 0x3a, 0xe6, 0x7b, 0xb0, 0xeb,
	0x81, 0xe3, 0x0f, 0x7b, 0x92, 0x69, 0x0c, 0xfb, 0xf4, 0x74, 0x2f, 0xae, 0x8e, 0xbf, 0x00, 0x93,
	0xfa, 0xcb, 0xaf, 0x49, 0xa8, 0x35, 0x55, 0xd3, 0x07, 0xfd, 0xa0, 0x2a, 0xec, 0x85, 0x89, 0x7f,
	0x92, 0x8f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x88, 0x0e, 0xba, 0x14, 0x3f, 0x07, 0x00, 0x00,
}
