// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/acct/acct.proto

package com_toyent_srv_acct

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpenRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRequest) Reset()         { *m = OpenRequest{} }
func (m *OpenRequest) String() string { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()    {}
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a2a0bf9ac2e58aa, []int{0}
}

func (m *OpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRequest.Unmarshal(m, b)
}
func (m *OpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRequest.Marshal(b, m, deterministic)
}
func (m *OpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRequest.Merge(m, src)
}
func (m *OpenRequest) XXX_Size() int {
	return xxx_messageInfo_OpenRequest.Size(m)
}
func (m *OpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRequest proto.InternalMessageInfo

func (m *OpenRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *OpenRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type OpenResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	AccountId            int64    `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance              float64  `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenResponse) Reset()         { *m = OpenResponse{} }
func (m *OpenResponse) String() string { return proto.CompactTextString(m) }
func (*OpenResponse) ProtoMessage()    {}
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a2a0bf9ac2e58aa, []int{1}
}

func (m *OpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenResponse.Unmarshal(m, b)
}
func (m *OpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenResponse.Marshal(b, m, deterministic)
}
func (m *OpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenResponse.Merge(m, src)
}
func (m *OpenResponse) XXX_Size() int {
	return xxx_messageInfo_OpenResponse.Size(m)
}
func (m *OpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenResponse proto.InternalMessageInfo

func (m *OpenResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *OpenResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OpenResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OpenResponse) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *OpenResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type QueryRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a2a0bf9ac2e58aa, []int{2}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type QueryResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Balance              float64  `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a2a0bf9ac2e58aa, []int{3}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type ChangeRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeRequest) Reset()         { *m = ChangeRequest{} }
func (m *ChangeRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeRequest) ProtoMessage()    {}
func (*ChangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a2a0bf9ac2e58aa, []int{4}
}

func (m *ChangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRequest.Unmarshal(m, b)
}
func (m *ChangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRequest.Marshal(b, m, deterministic)
}
func (m *ChangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRequest.Merge(m, src)
}
func (m *ChangeRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeRequest.Size(m)
}
func (m *ChangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRequest proto.InternalMessageInfo

func (m *ChangeRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *ChangeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ChangeRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ChangeResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Balance              float64  `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeResponse) Reset()         { *m = ChangeResponse{} }
func (m *ChangeResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeResponse) ProtoMessage()    {}
func (*ChangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a2a0bf9ac2e58aa, []int{5}
}

func (m *ChangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeResponse.Unmarshal(m, b)
}
func (m *ChangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeResponse.Marshal(b, m, deterministic)
}
func (m *ChangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeResponse.Merge(m, src)
}
func (m *ChangeResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeResponse.Size(m)
}
func (m *ChangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeResponse proto.InternalMessageInfo

func (m *ChangeResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *ChangeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ChangeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChangeResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*OpenRequest)(nil), "com.toyent.srv.acct.OpenRequest")
	proto.RegisterType((*OpenResponse)(nil), "com.toyent.srv.acct.OpenResponse")
	proto.RegisterType((*QueryRequest)(nil), "com.toyent.srv.acct.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "com.toyent.srv.acct.QueryResponse")
	proto.RegisterType((*ChangeRequest)(nil), "com.toyent.srv.acct.ChangeRequest")
	proto.RegisterType((*ChangeResponse)(nil), "com.toyent.srv.acct.ChangeResponse")
}

func init() { proto.RegisterFile("proto/acct/acct.proto", fileDescriptor_2a2a0bf9ac2e58aa) }

var fileDescriptor_2a2a0bf9ac2e58aa = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x35, 0xae, 0xeb, 0xd8, 0xe7, 0x26, 0x12, 0x51, 0x4b, 0x41, 0xa8, 0xf1, 0xd2, 0x53, 0x04,
	0xbd, 0xe8, 0x51, 0x3c, 0xed, 0x20, 0x6a, 0xfc, 0x01, 0x92, 0xa5, 0x61, 0x0e, 0x6c, 0x52, 0x9b,
	0x54, 0xd8, 0x6f, 0xf0, 0x2f, 0x7b, 0x90, 0xa4, 0xad, 0x6c, 0x50, 0x0b, 0x8a, 0x5e, 0x4a, 0x5f,
	0xf2, 0xde, 0x97, 0xf7, 0xf2, 0x7d, 0x81, 0x83, 0xa2, 0xd4, 0x56, 0x9f, 0x71, 0x21, 0xac, 0xff,
	0x50, 0x8f, 0xf1, 0xbe, 0xd0, 0x39, 0xb5, 0x7a, 0x25, 0x95, 0xa5, 0xa6, 0x7c, 0xa3, 0x6e, 0x8b,
	0x5c, 0xc2, 0xce, 0x5d, 0x21, 0x15, 0x93, 0xaf, 0x95, 0x34, 0x16, 0xef, 0xc1, 0xc0, 0x2c, 0xb3,
	0x08, 0x25, 0x28, 0x1d, 0x33, 0xf7, 0x8b, 0x8f, 0x60, 0x54, 0x19, 0x59, 0x3e, 0x2d, 0xb3, 0x68,
	0xdb, 0xaf, 0x86, 0x0e, 0xce, 0x32, 0xf2, 0x8e, 0x60, 0x52, 0x4b, 0x4d, 0xa1, 0x95, 0x91, 0x1d,
	0xda, 0x43, 0x08, 0x8d, 0xe5, 0xb6, 0x32, 0xad, 0xb4, 0x46, 0x38, 0x82, 0x51, 0x2e, 0x8d, 0xe1,
	0x0b, 0x19, 0x0d, 0xfc, 0x46, 0x0b, 0xf1, 0x31, 0x00, 0x17, 0x42, 0x57, 0xca, 0xba, 0x03, 0x83,
	0x04, 0xa5, 0x03, 0x36, 0x6e, 0x56, 0x66, 0x99, 0x13, 0xce, 0xf9, 0x0b, 0x57, 0x42, 0x46, 0xc3,
	0x04, 0xa5, 0x88, 0xb5, 0x90, 0x5c, 0xc1, 0xe4, 0xa1, 0x92, 0xe5, 0xea, 0x17, 0x41, 0x72, 0x98,
	0x36, 0xd2, 0x3f, 0x0c, 0xf2, 0xbd, 0x53, 0x06, 0xd3, 0x9b, 0x67, 0xae, 0x16, 0xf2, 0xe7, 0x56,
	0x9d, 0x0f, 0x9e, 0xbb, 0xbb, 0xf0, 0xc7, 0x21, 0xd6, 0x20, 0xa2, 0x60, 0xb7, 0xad, 0xf9, 0x3f,
	0x19, 0x82, 0x8d, 0x0c, 0xe7, 0x1f, 0x08, 0x82, 0x6b, 0x21, 0x2c, 0xbe, 0x85, 0xc0, 0xcd, 0x00,
	0x4e, 0x68, 0xc7, 0x70, 0xd1, 0xb5, 0xc9, 0x8a, 0x4f, 0x7a, 0x18, 0xb5, 0x67, 0xb2, 0x85, 0xef,
	0x61, 0xe8, 0x5b, 0x81, 0xbb, 0xd9, 0xeb, 0x1d, 0x8e, 0x49, 0x1f, 0xe5, 0xab, 0xe2, 0x23, 0x84,
	0xf5, 0xcd, 0xe0, 0x6e, 0xfe, 0x46, 0x2b, 0xe2, 0xd3, 0x5e, 0x4e, 0x5b, 0x74, 0x1e, 0xfa, 0x07,
	0x75, 0xf1, 0x19, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x2e, 0x45, 0xcd, 0x69, 0x03, 0x00, 0x00,
}
