// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/stock/stock.proto

package com_toyent_srv_stock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Stock struct {
	StockId              string   `protobuf:"bytes,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	StockName            string   `protobuf:"bytes,2,opt,name=stock_name,json=stockName,proto3" json:"stock_name,omitempty"`
	OpenPrice            float64  `protobuf:"fixed64,3,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	ClosePrice           float64  `protobuf:"fixed64,4,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	TradeDate            string   `protobuf:"bytes,5,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stock) Reset()         { *m = Stock{} }
func (m *Stock) String() string { return proto.CompactTextString(m) }
func (*Stock) ProtoMessage()    {}
func (*Stock) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{0}
}

func (m *Stock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stock.Unmarshal(m, b)
}
func (m *Stock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stock.Marshal(b, m, deterministic)
}
func (m *Stock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stock.Merge(m, src)
}
func (m *Stock) XXX_Size() int {
	return xxx_messageInfo_Stock.Size(m)
}
func (m *Stock) XXX_DiscardUnknown() {
	xxx_messageInfo_Stock.DiscardUnknown(m)
}

var xxx_messageInfo_Stock proto.InternalMessageInfo

func (m *Stock) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

func (m *Stock) GetStockName() string {
	if m != nil {
		return m.StockName
	}
	return ""
}

func (m *Stock) GetOpenPrice() float64 {
	if m != nil {
		return m.OpenPrice
	}
	return 0
}

func (m *Stock) GetClosePrice() float64 {
	if m != nil {
		return m.ClosePrice
	}
	return 0
}

func (m *Stock) GetTradeDate() string {
	if m != nil {
		return m.TradeDate
	}
	return ""
}

type Price struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{1}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Price) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Quot struct {
	StockId              string   `protobuf:"bytes,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	Price                []*Price `protobuf:"bytes,3,rep,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quot) Reset()         { *m = Quot{} }
func (m *Quot) String() string { return proto.CompactTextString(m) }
func (*Quot) ProtoMessage()    {}
func (*Quot) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{2}
}

func (m *Quot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quot.Unmarshal(m, b)
}
func (m *Quot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quot.Marshal(b, m, deterministic)
}
func (m *Quot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quot.Merge(m, src)
}
func (m *Quot) XXX_Size() int {
	return xxx_messageInfo_Quot.Size(m)
}
func (m *Quot) XXX_DiscardUnknown() {
	xxx_messageInfo_Quot.DiscardUnknown(m)
}

var xxx_messageInfo_Quot proto.InternalMessageInfo

func (m *Quot) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

func (m *Quot) GetPrice() []*Price {
	if m != nil {
		return m.Price
	}
	return nil
}

type QueryRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	StockId              string   `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{3}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryRequest) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

type QueryResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Stock                []*Stock `protobuf:"bytes,4,rep,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{4}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryResponse) GetStock() []*Stock {
	if m != nil {
		return m.Stock
	}
	return nil
}

type PriceRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	StockId              string   `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceRequest) Reset()         { *m = PriceRequest{} }
func (m *PriceRequest) String() string { return proto.CompactTextString(m) }
func (*PriceRequest) ProtoMessage()    {}
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{5}
}

func (m *PriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceRequest.Unmarshal(m, b)
}
func (m *PriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceRequest.Marshal(b, m, deterministic)
}
func (m *PriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceRequest.Merge(m, src)
}
func (m *PriceRequest) XXX_Size() int {
	return xxx_messageInfo_PriceRequest.Size(m)
}
func (m *PriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PriceRequest proto.InternalMessageInfo

func (m *PriceRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *PriceRequest) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

func (m *PriceRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type PriceResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceResponse) Reset()         { *m = PriceResponse{} }
func (m *PriceResponse) String() string { return proto.CompactTextString(m) }
func (*PriceResponse) ProtoMessage()    {}
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{6}
}

func (m *PriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceResponse.Unmarshal(m, b)
}
func (m *PriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceResponse.Marshal(b, m, deterministic)
}
func (m *PriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceResponse.Merge(m, src)
}
func (m *PriceResponse) XXX_Size() int {
	return xxx_messageInfo_PriceResponse.Size(m)
}
func (m *PriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PriceResponse proto.InternalMessageInfo

func (m *PriceResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *PriceResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PriceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QuotRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	StockId              string   `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	BeginTime            int64    `protobuf:"varint,3,opt,name=beginTime,proto3" json:"beginTime,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotRequest) Reset()         { *m = QuotRequest{} }
func (m *QuotRequest) String() string { return proto.CompactTextString(m) }
func (*QuotRequest) ProtoMessage()    {}
func (*QuotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{7}
}

func (m *QuotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotRequest.Unmarshal(m, b)
}
func (m *QuotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotRequest.Marshal(b, m, deterministic)
}
func (m *QuotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotRequest.Merge(m, src)
}
func (m *QuotRequest) XXX_Size() int {
	return xxx_messageInfo_QuotRequest.Size(m)
}
func (m *QuotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuotRequest proto.InternalMessageInfo

func (m *QuotRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QuotRequest) GetStockId() string {
	if m != nil {
		return m.StockId
	}
	return ""
}

func (m *QuotRequest) GetBeginTime() int64 {
	if m != nil {
		return m.BeginTime
	}
	return 0
}

func (m *QuotRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type QuotResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Quot                 *Quot    `protobuf:"bytes,4,opt,name=quot,proto3" json:"quot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotResponse) Reset()         { *m = QuotResponse{} }
func (m *QuotResponse) String() string { return proto.CompactTextString(m) }
func (*QuotResponse) ProtoMessage()    {}
func (*QuotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{8}
}

func (m *QuotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotResponse.Unmarshal(m, b)
}
func (m *QuotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotResponse.Marshal(b, m, deterministic)
}
func (m *QuotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotResponse.Merge(m, src)
}
func (m *QuotResponse) XXX_Size() int {
	return xxx_messageInfo_QuotResponse.Size(m)
}
func (m *QuotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuotResponse proto.InternalMessageInfo

func (m *QuotResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QuotResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QuotResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QuotResponse) GetQuot() *Quot {
	if m != nil {
		return m.Quot
	}
	return nil
}

type OpenTradeRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenTradeRequest) Reset()         { *m = OpenTradeRequest{} }
func (m *OpenTradeRequest) String() string { return proto.CompactTextString(m) }
func (*OpenTradeRequest) ProtoMessage()    {}
func (*OpenTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{9}
}

func (m *OpenTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenTradeRequest.Unmarshal(m, b)
}
func (m *OpenTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenTradeRequest.Marshal(b, m, deterministic)
}
func (m *OpenTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenTradeRequest.Merge(m, src)
}
func (m *OpenTradeRequest) XXX_Size() int {
	return xxx_messageInfo_OpenTradeRequest.Size(m)
}
func (m *OpenTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenTradeRequest proto.InternalMessageInfo

func (m *OpenTradeRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type OpenTradeResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenTradeResponse) Reset()         { *m = OpenTradeResponse{} }
func (m *OpenTradeResponse) String() string { return proto.CompactTextString(m) }
func (*OpenTradeResponse) ProtoMessage()    {}
func (*OpenTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{10}
}

func (m *OpenTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenTradeResponse.Unmarshal(m, b)
}
func (m *OpenTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenTradeResponse.Marshal(b, m, deterministic)
}
func (m *OpenTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenTradeResponse.Merge(m, src)
}
func (m *OpenTradeResponse) XXX_Size() int {
	return xxx_messageInfo_OpenTradeResponse.Size(m)
}
func (m *OpenTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenTradeResponse proto.InternalMessageInfo

func (m *OpenTradeResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *OpenTradeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OpenTradeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Stock)(nil), "com.toyent.srv.stock.stock")
	proto.RegisterType((*Price)(nil), "com.toyent.srv.stock.price")
	proto.RegisterType((*Quot)(nil), "com.toyent.srv.stock.quot")
	proto.RegisterType((*QueryRequest)(nil), "com.toyent.srv.stock.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "com.toyent.srv.stock.QueryResponse")
	proto.RegisterType((*PriceRequest)(nil), "com.toyent.srv.stock.PriceRequest")
	proto.RegisterType((*PriceResponse)(nil), "com.toyent.srv.stock.PriceResponse")
	proto.RegisterType((*QuotRequest)(nil), "com.toyent.srv.stock.QuotRequest")
	proto.RegisterType((*QuotResponse)(nil), "com.toyent.srv.stock.QuotResponse")
	proto.RegisterType((*OpenTradeRequest)(nil), "com.toyent.srv.stock.OpenTradeRequest")
	proto.RegisterType((*OpenTradeResponse)(nil), "com.toyent.srv.stock.OpenTradeResponse")
}

func init() { proto.RegisterFile("proto/stock/stock.proto", fileDescriptor_5f076fe61217ff59) }

var fileDescriptor_5f076fe61217ff59 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xee, 0xc6, 0x76, 0x8b, 0x27, 0xad, 0x54, 0x56, 0x15, 0x98, 0x40, 0x45, 0x58, 0x10, 0xe4,
	0x64, 0x44, 0x38, 0x72, 0xe5, 0xc2, 0x85, 0x92, 0x6d, 0x24, 0x6e, 0x44, 0x6e, 0x3c, 0xaa, 0x22,
	0xb0, 0xd7, 0xf5, 0xae, 0x91, 0x7a, 0xe5, 0xc0, 0x73, 0xf0, 0x68, 0x3c, 0x0a, 0xda, 0x59, 0x3b,
	0x4d, 0x90, 0xed, 0x4a, 0x51, 0x2e, 0xd6, 0xee, 0x7c, 0xdf, 0x7c, 0xf3, 0xbb, 0x86, 0xc7, 0x45,
	0xa9, 0x8c, 0x7a, 0xab, 0x8d, 0x5a, 0x7e, 0x77, 0xdf, 0x98, 0x2c, 0xfc, 0x6c, 0xa9, 0xb2, 0xd8,
	0xa8, 0x5b, 0xcc, 0x4d, 0xac, 0xcb, 0x9f, 0x31, 0x61, 0xe2, 0x0f, 0x83, 0x80, 0x4e, 0xfc, 0x09,
	0x3c, 0xa0, 0xc3, 0x62, 0x95, 0x46, 0x6c, 0xcc, 0x26, 0xa1, 0x3c, 0xa2, 0xfb, 0xa7, 0x94, 0x9f,
	0x03, 0x38, 0x28, 0x4f, 0x32, 0x8c, 0x06, 0x04, 0x86, 0x64, 0xf9, 0x9c, 0x64, 0x68, 0x61, 0x55,
	0x60, 0xbe, 0x28, 0xca, 0xd5, 0x12, 0x23, 0x6f, 0xcc, 0x26, 0x4c, 0x86, 0xd6, 0xf2, 0xc5, 0x1a,
	0xf8, 0x73, 0x18, 0x2e, 0x7f, 0x28, 0x8d, 0x35, 0xee, 0x13, 0x0e, 0x64, 0x72, 0x84, 0x73, 0x00,
	0x53, 0x26, 0x29, 0x2e, 0xd2, 0xc4, 0x60, 0x14, 0x38, 0x79, 0xb2, 0x7c, 0x4c, 0x0c, 0x8a, 0x77,
	0x10, 0x90, 0x27, 0xe7, 0xe0, 0x9b, 0x55, 0x86, 0x94, 0x9d, 0x27, 0xe9, 0xcc, 0xcf, 0x6a, 0x90,
	0xb2, 0x62, 0xd2, 0x5d, 0xc4, 0x1c, 0xfc, 0x9b, 0x4a, 0x99, 0xbe, 0x9a, 0x1a, 0xd5, 0xc8, 0x1b,
	0x7b, 0x93, 0xe1, 0xf4, 0x69, 0xdc, 0xd6, 0x9e, 0x98, 0x28, 0x8d, 0xea, 0x07, 0x38, 0x9e, 0x55,
	0x58, 0xde, 0x4a, 0xbc, 0xa9, 0x50, 0x1b, 0x7e, 0x0a, 0x9e, 0x5e, 0x0b, 0xdb, 0xe3, 0x56, 0xbc,
	0xc1, 0x56, 0x3c, 0xf1, 0x9b, 0xc1, 0x49, 0xed, 0xad, 0x0b, 0x95, 0x6b, 0x6c, 0x71, 0x7f, 0x04,
	0x87, 0xda, 0x24, 0xa6, 0xd2, 0xb5, 0x73, 0x7d, 0xe3, 0x11, 0x1c, 0x65, 0xa8, 0x75, 0x72, 0xed,
	0xba, 0x1b, 0xca, 0xe6, 0x6a, 0xab, 0xa0, 0x00, 0x91, 0xdf, 0x57, 0x05, 0x7d, 0xa5, 0x63, 0x8a,
	0x19, 0x1c, 0x53, 0xdb, 0x77, 0xa9, 0xe2, 0xae, 0xdd, 0xde, 0x66, 0xbb, 0x2f, 0xe1, 0xa4, 0x96,
	0xdc, 0x5f, 0x69, 0xa2, 0x84, 0xe1, 0xac, 0x52, 0x66, 0xa7, 0x34, 0x9f, 0x41, 0x78, 0x85, 0xd7,
	0xab, 0x7c, 0x6e, 0xd7, 0xc5, 0xa3, 0x75, 0xb9, 0x33, 0xd8, 0x98, 0x98, 0xa7, 0x84, 0xf9, 0x84,
	0x35, 0x57, 0xf1, 0x8b, 0xd9, 0x11, 0xdb, 0xa0, 0x7b, 0x9c, 0x51, 0xec, 0x96, 0x91, 0x62, 0x0d,
	0xa7, 0xa3, 0xf6, 0x11, 0x59, 0x86, 0x24, 0x9e, 0x78, 0x05, 0xa7, 0x17, 0x05, 0xe6, 0x73, 0xfb,
	0x00, 0x3a, 0xab, 0x17, 0x5f, 0xe1, 0xe1, 0x06, 0x6b, 0x7f, 0xe9, 0x4e, 0xff, 0x0e, 0x20, 0xb8,
	0xa4, 0x3f, 0x82, 0x84, 0x80, 0x36, 0x96, 0x8b, 0xf6, 0x9c, 0x37, 0x1f, 0xc3, 0xe8, 0x65, 0x2f,
	0xc7, 0xe5, 0x27, 0x0e, 0xac, 0xa6, 0x7b, 0xf4, 0x1d, 0x9a, 0x9b, 0xab, 0xd9, 0xa5, 0xb9, 0xb5,
	0x6b, 0xe2, 0x80, 0x5f, 0x80, 0x6f, 0x87, 0xc6, 0x5f, 0x74, 0xa5, 0xb0, 0xde, 0xa2, 0x91, 0xe8,
	0xa3, 0xac, 0x05, 0xbf, 0x41, 0xb8, 0xee, 0x2d, 0x7f, 0xdd, 0xee, 0xf2, 0xff, 0x88, 0x46, 0x6f,
	0xee, 0xe5, 0x35, 0xfa, 0x57, 0x87, 0xf4, 0x47, 0x7e, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xe6,
	0x40, 0x80, 0x9b, 0xac, 0x05, 0x00, 0x00,
}
