// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package com_toyent_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpenRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRequest) Reset()         { *m = OpenRequest{} }
func (m *OpenRequest) String() string { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()    {}
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *OpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRequest.Unmarshal(m, b)
}
func (m *OpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRequest.Marshal(b, m, deterministic)
}
func (m *OpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRequest.Merge(m, src)
}
func (m *OpenRequest) XXX_Size() int {
	return xxx_messageInfo_OpenRequest.Size(m)
}
func (m *OpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRequest proto.InternalMessageInfo

func (m *OpenRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *OpenRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OpenRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *OpenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type OpenResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenResponse) Reset()         { *m = OpenResponse{} }
func (m *OpenResponse) String() string { return proto.CompactTextString(m) }
func (*OpenResponse) ProtoMessage()    {}
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *OpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenResponse.Unmarshal(m, b)
}
func (m *OpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenResponse.Marshal(b, m, deterministic)
}
func (m *OpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenResponse.Merge(m, src)
}
func (m *OpenResponse) XXX_Size() int {
	return xxx_messageInfo_OpenResponse.Size(m)
}
func (m *OpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenResponse proto.InternalMessageInfo

func (m *OpenResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *OpenResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OpenResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type QueryResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *QueryResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type AuthRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *AuthRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *AuthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AuthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenRequest)(nil), "com.toyent.srv.user.OpenRequest")
	proto.RegisterType((*OpenResponse)(nil), "com.toyent.srv.user.OpenResponse")
	proto.RegisterType((*QueryRequest)(nil), "com.toyent.srv.user.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "com.toyent.srv.user.QueryResponse")
	proto.RegisterType((*AuthRequest)(nil), "com.toyent.srv.user.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "com.toyent.srv.user.AuthResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x6d, 0x68, 0x9a, 0xb6, 0xd7, 0x22, 0x21, 0x23, 0x20, 0x0a, 0x4b, 0xf1, 0xc4, 0x64, 0x24,
	0x98, 0x18, 0x19, 0x19, 0xca, 0x47, 0x04, 0x33, 0x0a, 0xe4, 0x04, 0x1d, 0x12, 0xa7, 0x3e, 0x07,
	0xd4, 0x9f, 0xc0, 0x1f, 0x66, 0x46, 0xb6, 0x09, 0x32, 0x22, 0xa9, 0x04, 0xea, 0x12, 0xe5, 0xf9,
	0x2e, 0x7e, 0xef, 0xde, 0xbb, 0xc0, 0x5e, 0xa5, 0xa4, 0x96, 0x27, 0x35, 0xa1, 0xb2, 0x0f, 0x61,
	0x31, 0xdb, 0x7d, 0x92, 0x85, 0xd0, 0x72, 0x85, 0xa5, 0x16, 0xa4, 0x5e, 0x85, 0x29, 0xf1, 0x25,
	0x4c, 0xae, 0x2b, 0x2c, 0x53, 0x5c, 0xd6, 0x48, 0x9a, 0xed, 0x40, 0x9f, 0x16, 0x79, 0x1c, 0xcc,
	0x82, 0xe3, 0x71, 0x6a, 0x5e, 0xd9, 0x01, 0x0c, 0x4d, 0xe3, 0xc3, 0x22, 0x8f, 0xb7, 0xec, 0x69,
	0x64, 0xe0, 0x65, 0xce, 0x0e, 0x61, 0x6c, 0x0b, 0x65, 0x56, 0x60, 0xdc, 0xb7, 0xa5, 0x91, 0x39,
	0xb8, 0xca, 0x0a, 0x64, 0x09, 0x8c, 0xaa, 0x8c, 0xe8, 0x4d, 0xaa, 0x3c, 0x0e, 0x5d, 0xad, 0xc1,
	0x3c, 0x85, 0xa9, 0xa3, 0xa4, 0x4a, 0x96, 0x84, 0x2d, 0x9c, 0xfb, 0x10, 0x91, 0xce, 0x74, 0x4d,
	0x0d, 0xa5, 0x43, 0x2c, 0x86, 0x61, 0x81, 0x44, 0xd9, 0x73, 0x43, 0xd8, 0x40, 0x7e, 0x0e, 0xd3,
	0xdb, 0x1a, 0xd5, 0xea, 0xef, 0x73, 0xf0, 0xf7, 0x00, 0xb6, 0xbf, 0xbe, 0xdd, 0x9c, 0x20, 0x9f,
	0x2e, 0xec, 0xb6, 0x6d, 0xf0, 0xd3, 0x36, 0x7e, 0x07, 0x93, 0x8b, 0x5a, 0xbf, 0xfc, 0x23, 0x0d,
	0xdf, 0xf0, 0xfe, 0x6f, 0xc3, 0xdd, 0xad, 0x9b, 0x9b, 0xef, 0xf4, 0x23, 0x80, 0xf0, 0x9e, 0x50,
	0xb1, 0x39, 0x84, 0x26, 0x4d, 0x36, 0x13, 0x2d, 0xeb, 0x25, 0xbc, 0xdd, 0x4a, 0x8e, 0xd6, 0x74,
	0x38, 0x65, 0xbc, 0xc7, 0x6e, 0x60, 0x60, 0xc3, 0x60, 0xed, 0xdd, 0x7e, 0xc8, 0x09, 0x5f, 0xd7,
	0xf2, 0x7d, 0xe3, 0x1c, 0x42, 0x33, 0x7d, 0x87, 0x40, 0xcf, 0xee, 0x0e, 0x81, 0xbe, 0x75, 0xbc,
	0xf7, 0x18, 0xd9, 0x9f, 0xe9, 0xec, 0x33, 0x00, 0x00, 0xff, 0xff, 0x33, 0xab, 0xc5, 0x9e, 0x65,
	0x03, 0x00, 0x00,
}
