// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package com_toyent_web_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegRequest) Reset()         { *m = RegRequest{} }
func (m *RegRequest) String() string { return proto.CompactTextString(m) }
func (*RegRequest) ProtoMessage()    {}
func (*RegRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *RegRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegRequest.Unmarshal(m, b)
}
func (m *RegRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegRequest.Marshal(b, m, deterministic)
}
func (m *RegRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegRequest.Merge(m, src)
}
func (m *RegRequest) XXX_Size() int {
	return xxx_messageInfo_RegRequest.Size(m)
}
func (m *RegRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegRequest proto.InternalMessageInfo

func (m *RegRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *RegRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Balance              float64  `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegResponse) Reset()         { *m = RegResponse{} }
func (m *RegResponse) String() string { return proto.CompactTextString(m) }
func (*RegResponse) ProtoMessage()    {}
func (*RegResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *RegResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegResponse.Unmarshal(m, b)
}
func (m *RegResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegResponse.Marshal(b, m, deterministic)
}
func (m *RegResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegResponse.Merge(m, src)
}
func (m *RegResponse) XXX_Size() int {
	return xxx_messageInfo_RegResponse.Size(m)
}
func (m *RegResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegResponse proto.InternalMessageInfo

func (m *RegResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *RegResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RegResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type LoginRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *LoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *LoginResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type QueryResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Balance              float64  `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *QueryResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *QueryResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *QueryResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*RegRequest)(nil), "com.toyent.web.user.RegRequest")
	proto.RegisterType((*RegResponse)(nil), "com.toyent.web.user.RegResponse")
	proto.RegisterType((*LoginRequest)(nil), "com.toyent.web.user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "com.toyent.web.user.LoginResponse")
	proto.RegisterType((*QueryRequest)(nil), "com.toyent.web.user.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "com.toyent.web.user.QueryResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0x5d, 0xbb, 0xbb, 0xe3, 0x2e, 0x48, 0x44, 0x0d, 0x7a, 0x91, 0x9c, 0x3c, 0xd5,
	0x83, 0x27, 0x7f, 0x82, 0x20, 0x82, 0x15, 0xcf, 0x92, 0x6e, 0x87, 0x52, 0xb4, 0x49, 0xed, 0x24,
	0x2c, 0xfb, 0x7b, 0xfc, 0xa3, 0x92, 0xd9, 0x0d, 0xd4, 0x45, 0x0f, 0x4a, 0x2f, 0xa5, 0x6f, 0x5e,
	0x9b, 0x2f, 0x2f, 0x2f, 0x70, 0xda, 0xf5, 0xd6, 0xd9, 0x1b, 0x4f, 0xd8, 0xf3, 0x23, 0x67, 0x2d,
	0x4e, 0x56, 0xb6, 0xcd, 0x9d, 0xdd, 0xa0, 0x71, 0xf9, 0x1a, 0xcb, 0x3c, 0x58, 0xaa, 0x03, 0x28,
	0xb0, 0x2e, 0xf0, 0xc3, 0x23, 0x39, 0x71, 0x0c, 0x29, 0x35, 0x95, 0x4c, 0xae, 0x92, 0xeb, 0x79,
	0x11, 0x5e, 0xc5, 0x39, 0x4c, 0xc3, 0x77, 0xaf, 0x4d, 0x25, 0x0f, 0x78, 0x9a, 0x05, 0x79, 0x5f,
	0x89, 0x4b, 0x98, 0xb3, 0x61, 0x74, 0x8b, 0x32, 0x65, 0x6b, 0x16, 0x06, 0x8f, 0xba, 0x45, 0x71,
	0x01, 0xb3, 0x4e, 0x13, 0xad, 0x6d, 0x5f, 0xc9, 0xc9, 0xd6, 0x8b, 0x5a, 0xbd, 0xc1, 0x11, 0x13,
	0xa9, 0xb3, 0x86, 0xf0, 0x07, 0xe4, 0x19, 0x64, 0xe4, 0xb4, 0xf3, 0x14, 0x89, 0x5b, 0x25, 0x24,
	0x4c, 0x5b, 0x24, 0xd2, 0x75, 0xe4, 0x45, 0x19, 0x9c, 0x52, 0xbf, 0x6b, 0xb3, 0x42, 0xa6, 0x25,
	0x45, 0x94, 0xea, 0x05, 0x16, 0x0f, 0xb6, 0x6e, 0xcc, 0x3f, 0x02, 0x0e, 0x33, 0xa4, 0x7b, 0x19,
	0x9e, 0x61, 0xb9, 0x5b, 0x76, 0xbc, 0x14, 0xea, 0x0e, 0x16, 0x4f, 0x1e, 0xfb, 0xcd, 0xdf, 0xf7,
	0xaa, 0x3e, 0x13, 0x58, 0xee, 0xfe, 0x1d, 0xf1, 0x58, 0x07, 0xb8, 0xc9, 0xef, 0xdd, 0x1f, 0xee,
	0x75, 0x3f, 0x28, 0x23, 0xfb, 0x56, 0x46, 0x99, 0xf1, 0x3d, 0xbc, 0xfd, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x8e, 0x12, 0xbe, 0xea, 0xa0, 0x02, 0x00, 0x00,
}
